import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import {
  About,
  Contact,
  Header,
  Hero,
  Projects,
  Skills,
  WorkEexperience,
} from "../components";
import image from "../assets/me.jpg";
import Image from "next/image";
import { Experience, PageInfo, Project, Skill, Social } from "../types";
import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchExperience } from "../utils/fetchExperience";
import { fetchSocials } from "../utils/fetchSocials";
import { fetchProjects } from "../utils/fetchProjects";
import { fetchSkills } from "../utils/fetchSkills";

type Props = {
  pageInfo: PageInfo;
  experience: Experience[];
  skills: Skill[];
  projects: Project[];
  socials: Social[];
};

const Home = ({ experience, skills, projects, socials ,pageInfo}: Props) => {

  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y overflow-y-scroll overflow-x-hidden z-0 snap-mandatory scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#FA7B0A]/80">
      <Head>
        <title>Adefope Oluwatosin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header social={socials} />
      <section id="hero" className="snap-center">
        <Hero pageInfo={pageInfo} />
      </section>
      <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section>
      <section id="experience" className="snap-center">
        <WorkEexperience experience={experience} />
      </section>
      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>
      <section id="projects" className="snap-start">
        <Projects projects={projects}/>
      </section>
      <section id="contact" className="snap-start">
        <Contact />
      </section>
      <Link href="#hero">
        <footer className="sticky bottom-3 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <Image
              width={50}
              height={50}
              className="rounded-full w-10 h-10 filter grayscale hover:grayscale-0 cursor-pointer"
              src={image}
              alt=""
            />
          </div>
        </footer>
      </Link>
    </div>
  );
};

export default Home;

export const getServerSideProps:GetServerSideProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const skills: Skill[] = await fetchSkills();
  const experience: Experience[] = await fetchExperience();
  const socials: Social[] = await fetchSocials();
  const projects: Project[] = await fetchProjects();
  return {
    props: {
      pageInfo,
      experience,
      socials,
      skills,
      projects,
    }
  };
};
